# Generated by Django 4.2.3 on 2023-11-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
